:PROPERTIES:
:ID:       17721E2B-106A-4106-993A-ED61ECE480A0
:END:
#+title: Linear Algebra

#+Refrences: Gilbert Strang Book

* Intro

- The linear of combination of \(\vec{v}\) and \(\vec{w}\) gives a vector in the
  same plane as both  \(\vec{v}\) and  \(\vec{w}\).

- The central problem of linear algebra is the solution of the linear equations
- The main important case being the "n equations with n no od unknowms".
- Two ways of solving:
  - Elimination method:
    - Here using 2 equations from the given n , any one variable is eliminated.
      The elimination is carried out by applying the arithmetic operations on
      a single variable and eliminating that variable. Now the equations become
      n-1 with n-1 unknowns. This is continued till a single variable with single
      unknown is reached. After getting the value for a single variable that value
      is substituted to the previous equations which gives values to all the
      unknowns. So this is using forward elimination and backward substitution.
  - Cramers Rule:
    - Here the solutions of the equations is found by using the idea of determinants.
      The correct values of unknows us obtained by using Cramers rule where
      ratio of two n*n determinants gives the solution.
    - A bit complicated and cannt be used in paper after n=4.
- So the method of elimination is used in its modified form, known as Gaussian
  Elimination.

- The systems of Linear equations can be represented in two ways:
  - For three dimensional space
    - Here the equation is represented as column vectors scaled by some scalars
      and added to give the solutions.

      \begin{align}
      2u + v + w = 5\\
      4u - 6v = -2\\
      -2u + 7v + 2w = 9\\
      \end{align}


  - Row form:
    - Here each planes (in 3d ) can be plotted in the 3d graph and the point of
      intersection is the solution of that system of linear equations.
    - Martix Form:
      - This equation can be represented as :


\[
\begin{bmatrix} 2 & 1 & 1 \\ 4 & -6 & 0 \\ -2 & 7 & 2 \end{bmatrix}*
\begin{bmatrix} x \\ y \\ z \end{bmatrix} =
\begin{bmatrix} 5 \\ 2 \\ 9 \end{bmatrix}.
\]

    - This is generally written as *Ax = b*

  - Columns Form:

    - This form of linear equation is represented as :


\[
u \begin{bmatrix} 2 \\ 4 \\ -2 \end{bmatrix} +
v \begin{bmatrix} 1 \\ -6 \\ 7 \end{bmatrix} +
w \begin{bmatrix} 1 \\ 0 \\ 2 \end{bmatrix} =
\begin{bmatrix} 5 \\ -2 \\ 9 \end{bmatrix} = b.
\]
- This is represented as linear combination ( as each column is multiplied by some
  linear/scalars) of the column vectors of system of linear equation.


* Gaussian Elimination :
- The central problem is to find the values of n unknows from n equations (linear)

** Steps
#+begin_example
- Pivot is the value which is used to eliminate the first unknown from all the
  suqsequent equations.
- Find the value of multiplier to multiply pivot.
- The value of multiplier is chosen such that a single unknown variable is eliminated from all the other equations rather than the first equation.
- Multiply equation 1 with multiplier.
- Substract equation 2 from 1. Continue for all the other equations.
- Now there are n-1 equations with n-1 unknowns.
- Continue this till you get 1 unknown and a single equation.
- Substitute the value in previous equations.
#+end_example

** Cases of Failures:
- This is the cases for which there is no single solution for the equations.
- The solution of the equations amounts to a single point where all the equations
  intersect.
  - If all the  planes  are parallel.=> no soluton
  - If any of the planes are parallel to the other.=> inconsistent solution
  - If adding two gives third or there is no intersection between the sum of two
    and the third. => inconsistent solution
  - if they intersect to form a plane rather than a plane. =>(infinity of solutions)too many solutions
- This can also be interpreted in terms of pivot as :
  - If Pivot is zero then this fails as there is no number that multiplies to zero
    to get to the number of second equation to eliminate that number from the
    second equation.
    - This can be avoided by exchanging the rows so that there is no zero at the
      pivot pivot position.
    - If the zero was at the last pivot then it would be a complete failure.
      [[https://youtu.be/QVKj3LADCnA?list=PL49CF3715CB9EF31D&t=873][complete failure]]
- This can also be interpreted in term of columns form as :
  - If the linear combination of the columns are in the same plane and :
    - There is a solution for the system of equation is the b is also on the same plane.
    - There is no solution if b is not on the same plane.[[mpv:https://www.youtube.com/watch?v=ZK3O402wf1c::00:32:11][failure i n column form]].
      -The matrix is singular in this case.
      - Matrix is not invertible and system has no solution.

    - The linearly dependent of a column with another column is that a column is just some
      scalar multiple of the another .
      - In this case the no of equations is n-1 ( as two euqations are soemhow same )
      - Also the system of equation is not solvabe ( or gives a plane as a solution rather
	than a single point ) that intersects all the planes of n-dimension.
	[[mpv:https://www.youtube.com/watch?v=ZK3O402wf1c::00:35:14][plane solution in case of linear dependence]]
- *Ax* is generally thought as dot product of *A* and *x* . i.e in row form .
- This can also be written as linear combination of columns.
- Example:

\[
\begin{bmatrix} 2 & 5  \\ 1 & 3  \end{bmatrix}*
\begin{bmatrix} 1 \\ 2 \\ \end{bmatrix}.
\]
- This can be written as :
  1.In terms of linear combination as :
\[
1\begin{bmatrix} 2\\1\end{bmatrix}+
2\begin{bmatrix} 5\\3\end{bmatrix}=
\begin{bmatrix} 12\\7\end{bmatrix}.
\]
2. In terms of row form as :
\[
\begin{bmatrix} 2*1+5*2\\1*1+3*21\end{bmatrix}=
\begin{bmatrix} 12\\7\end{bmatrix}.
\]
